# The primary k-mer parameters to use for calculating GAMBIT signatures
kmerparams:
  k: 11
  prefix: ATGAC


# Parameters for FastANI
fastani:
  k: 16  # Default
  fraglen: 3000  # Default


# How to download the GAMBIT database files
gambit_db:
  base_url: "https://storage.googleapis.com/hesslab-gambit-public/databases/refseq-curated/1.0-beta"
  genomes_file: gambit-genomes-1.0b1-210719.db
  signatures_file: gambit-signatures-1.0b1-210719.h5


# Parameter space for figure 2
fig2_params:
  k: [7, 9, 11, 13, 15]
  prefix_len: [4, 5, 6, 7]
  # First is our standard ATGAC plus two random nucleotides, remaining seven are randomly generated
  base_prefix:
    - ATGACTG
    - ATCATTT
    - TCTCGAT
    - GAAAGCG
    - TTGACCC
    - CACATAT
    - CGTTAGT
    - ACTCTTG


# Parameters tailored to specific genome sets
genome_sets:
  ondov_2016:
    # This one has way more genomes than the others, divide FastANI queries into chunks
    fastani_chunk_size: 10
