# Override parameters in main config file for testing
# Use this by adding
#   --config test=1
# to the command line options.


gambit_param_space:
  k: [9, 11]
  prefix_len: [4, 5]
  base_prefix:
    - ATGACTG
    - ATCATTT

benchmarks:
  replicates: 2
