# If we're running in test mode. Override this from the command line.
test: false


# Standard parameters for GAMBIT command line
gambit:
  k: 11
  prefix: ATGAC


# Parameters for FastANI
fastani:
  k: 16  # Default
  fraglen: 3000  # Default
  # Chunk queries so output matrices are no bigger than this
  chunk_size: 5000


# URLs for downloading source files
src_data:
  gambit_db:
    genomes: "hesslab-gambit-public/databases/refseq-curated/1.0-beta/gambit-genomes-1.0b1-210719.db"
    signatures: "hesslab-gambit-public/databases/refseq-curated/1.0-beta/gambit-signatures-1.0b1-210719.h5"

  genome_sets:
    set3:
      fasta: "hesslab-gambit-public/genomes/set3/fasta/"
      fastq: "hesslab-gambit-public/genomes/set3/fastq/"
    figure_6:
      tarball: "hesslab-gambit-public/genomes/figure-6/fasta.tar.gz"

  ncbi:
    # Use HTTP protocol to access NCBI FTP server files instead of FTP (have had issues on some networks)
    use_http: false


figure_2:
  # Parameter values to use with grid search
  k: [7, 9, 11, 13, 15]
  prefix_len: [4, 5, 6, 7]
  base_prefix:
    # Standard ATGAC plus two random nucleotides:
    - ATGACTG
    # Remaining are randomly generated:
    - ATCATTT
    - TCTCGAT
    - GAAAGCG
    - TTGACCC
    - CACATAT
    - CGTTAGT
    - ACTCTTG
